meteosite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('previsions.urls')),
    path('admin/', admin.site.urls),
]

previsions/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView
from django.contrib.auth.views import LogoutView
from . import views

app_name = 'previsions'
urlpatterns = [
    path('', views.index, name='index'),
    path('departements/', views.departements, name='departements'),
    path('select_departement/', views.select_departement, name='select_departement'),
    path('display_villes/', views.display_villes, name='display_villes'),
    path('add_ville/', views.add_ville, name='add_ville'),
    path('login/', LoginView.as_view(next_page='/'), name='login'),
    path('logout/', LogoutView.as_view(next_page='/login'), name='logout'),
    path('favoris/', views.favoris, name='favoris'),
    path('departement_client/', views.departement_client, name='departement_client'),
    path('display_previsions_ville/', views.display_previsions_ville, name='display_previsions_ville'),
]

previsions/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Departement(models.Model):
    id_departement = models.SmallAutoField(primary_key=True)
    nom = models.CharField(max_length=50, blank=True, null=True)
    code = models.CharField(max_length=3)

    def __str__(self):
        return self.nom

    class Meta:
        managed = True
        db_table = 'departement'


class Prevision(models.Model):
    id_prevision = models.AutoField(primary_key=True)
    temperature = models.DecimalField(max_digits=5, decimal_places=2)
    temperature_min = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    temperature_max = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    temperature_matin = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    temperature_apres_midi = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    temperature_nuit = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    presion = models.IntegerField(blank=True, null=True)
    humidite = models.IntegerField(blank=True, null=True)
    description = models.CharField(max_length=30)
    direction_vent = models.SmallIntegerField(blank=True, null=True)
    force_vent = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True)
    jour = models.DateField()
    last_update = models.DateField()
    id_ville = models.ForeignKey('Ville', models.DO_NOTHING, db_column='id_ville')

    class Meta:
        managed = True
        db_table = 'prevision'


class Ville(models.Model):
    id_ville = models.AutoField(primary_key=True)
    nom = models.CharField(max_length=60, blank=True, null=True)
    id_departement = models.ForeignKey(Departement, models.DO_NOTHING, db_column='id_departement')
    code_postal = models.IntegerField()

    def __str__(self):
        return self.nom

    class Meta:
        managed = True
        db_table = 'ville'

previsions/forms.py
from crispy_bulma.layout import Row, Column, Submit
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field
from django import forms
from .models import Departement
from django.forms import ModelChoiceField


class DepartementModelChoiceField(ModelChoiceField):
    def label_from_instance(self, obj):
        return obj.nom


class VilleForm(forms.Form):
    nom = forms.CharField(label='Nom', max_length=60, required=True)
    code_postal = forms.IntegerField(widget=forms.TextInput, label="Code postal", required=True)
    departement = DepartementModelChoiceField(label="Département",
                                              required=True,
                                              queryset=Departement.objects.all(),
                                              empty_label="(Choisir un département)",
                                              )


class DepartClientForm(forms.Form):
    departement = DepartementModelChoiceField(label="Département",
                                              required=True,
                                              queryset=Departement.objects.all(),
                                              empty_label="(Choisir un département)",
                                              widget=forms.Select(attrs={'onchange': 'submit();'},),
                                              )

previsions/views.py
from django.core.paginator import Paginator
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from django.contrib.auth.decorators import login_required
import logging

from .business.components.meteo_ville_previsions import MeteoVillePrevisions
from .models import Ville
from .models import Departement
from .forms import VilleForm, DepartClientForm
from .utils.helper.ui_helper import UIHelper

logger = logging.getLogger("django")


# @login_required(login_url=f'/login/?next=/previsions/login/')
def index(request):
    logger.debug("entrée dans la view 'Index'")
    template = loader.get_template('previsions/index.html')
    context = {}
    logger.warning('le contexte pour la view est vide')

    # ajout des villes favorites à la sessions utilisateur (simulation d'une sélection
    # déjà faite par l'utilisateur
    logger.info(f"Définition des villes favorites pour l'utilisateur")
    # liste_villes_favorites = ['Paris', 'Lyon', 'Strasbourg']
    # request.session['favoris'] = liste_villes_favorites

    logger.debug("sortie dans la view 'Index', rendu du tempate...")

    return HttpResponse(template.render(context, request))


def departements(request):
    # on obtient ici toutes les villes dont la clée étrangère est égale à 1
    #
    # ce qui correspond à la requête SQL :
    # select * from ville where id_departement = 1
    villes_du_departement = Ville.objects.filter(id_departement=1).order_by('nom')
    nom_departement = "Ain"

    # maintenant que nous avons les données, nous allons les associer
    # au context. Ainsi le Template pourra les utiliser pour générer l'affichage
    # avec les données.
    context = {
        'villes_du_departement': villes_du_departement,
        'nom_departement': nom_departement,
    }

    # nous pouvons utiliser un objet template pour générer l'affichage puis
    # le retourner via un objet HttpResponse mais... django propose
    # une methode 'render' qui le fait pour nous, alors utilisons la :-)
    return render(request, 'previsions/departements.html', context)


def select_departement(request):
    # on obtient la liste de tous les départements en BDD
    #
    # Se référer à la documentation django pour les requêtes de sélection d'objets
    # https://docs.djangoproject.com/fr/4.1/topics/db/queries/
    #
    liste_departements = Departement.objects.all()

    # on associe les données au context pour que le template puisse les utiliser
    context = {
        'liste_departements': liste_departements,
    }

    # on s'appuie sur Djangon pour initialiser le template et renvoyer le résultat
    return render(request, 'previsions/select_departement.html', context)


def display_villes(request):
    # on récupère le choix réalisé par l'utilisateur dans le formulaire
    # via l'objet request.
    # NB : le nom de l'élément HTML "select" est id_departement, la valeur ici
    # est celle de l'élément "option" choisi par l'utilisateur
    id_departement = request.POST['id_departement']

    # on obtient la liste de tous les départements en BDD
    #
    # Se référer à la documentation django pour les requêtes de sélection d'objets
    # https://docs.djangoproject.com/fr/4.1/topics/db/queries/
    #
    departement = Departement.objects.get(pk=id_departement)
    villes_du_departement = Ville.objects.filter(id_departement=id_departement).order_by('nom')

    # on associe les données au context pour que le template puisse les utiliser
    context = {
        'villes_du_departement': villes_du_departement,
        'departement': departement,
    }

    # on s'appuie sur Djangon pour initialiser le template et renvoyer le résultat
    return render(request, 'previsions/display_villes.html', context)


def add_ville(request):
    save_error = False
    is_create = True

    if request.method == 'POST':

        # on reçoit les données du formulaire, donc on n'est pas en mode création pour l'ajout
        # d'une nouvelle ville en BDD
        is_create = False

        # crée une instance du formulaire et remplie les champs avec les données présentes dans l'objet request
        form = VilleForm(request.POST)
        # la class form de Django permet de valider automatiquement les données utilisateur
        # lors de la saisie dans la navigateur, mais aussi lors de l'enregistrement en base de données
        if form.is_valid():

            # récupération des valeur du formulaire
            nom = form.cleaned_data["nom"]
            code_postal = form.cleaned_data["code_postal"]
            departement = form.cleaned_data["departement"]

            try:
                # enregistrement en base de données
                print("enregistrement de la ville en BDD...")
                ville = Ville()
                ville.nom = nom
                ville.code_postal = code_postal
                ville.id_departement = departement
                ville.save()

                print("enregistrement ok.")

                # maintenant que l'enregistrement est réalisé, on en permet un nouveau en créeant une nouvelle instance
                # pour cela
                form = VilleForm()

            except:
                save_error = True


    # Si l'on est pas sur la soumission de données, alors c'est que nous sommes en saisie de données
    # dans le formulaire, on fournit donc une instance de forumulaire
    else:
        form = VilleForm()

    return render(request, 'previsions/add_ville.html',
                  {'form': form, 'save_error': save_error, 'is_create': is_create})


def favoris(request):
    # Récupération des favoris depuis la liste stockée en session
    liste_villes_favorites = request.session['favoris']

    context = {
        'favoris': liste_villes_favorites,
    }

    return render(request, 'previsions/favoris.html', context)


def departement_client(request):
    # instanciation du formulaire
    form = DepartClientForm()

    liste_departements = Departement.objects.all()
    id_departement = 0
    page_obj = {}

    if request.method == 'POST':
        # crée une instance du formulaire et remplie les champs avec les données présentes dans l'objet request
        form = DepartClientForm(request.POST)

        # la class form de Django permet de valider automatiquement les données utilisateur
        # lors de la saisie dans la navigateur, mais aussi lors de l'enregistrement en base de données
        if form.is_valid():  # Forms only get a cleaned_data attribute when is_valid() has been called
            id_departement = form.cleaned_data["departement"]
            villes_du_departement = Ville.objects.filter(id_departement=id_departement).order_by('nom')
            paginator = Paginator(villes_du_departement, 20)

            page_number = request.GET.get('page')

            page_obj = paginator.get_page(page_number)

    context = {
        'liste_departements': liste_departements,
        'id_departement': id_departement,
        'form': form,
        'page_obj': page_obj,
    }

    return render(request, 'previsions/departement_client.html', context)


def display_previsions_ville(request):
    # on récupère la ville provenant du formulaire
    nom_ville = request.POST['ville']

    # on récupère les prévisions associées à la ville depuis la couche business
    meteo_ville_previsions = MeteoVillePrevisions(nom_ville)

    previsions_jour = meteo_ville_previsions.get_previsions_jour()
    previsions_force_vent = meteo_ville_previsions.get_previsions_force_vent()
    previsions_description = meteo_ville_previsions.get_previsions_description()

    # on construit une liste contenant des dictionnaires afin de pouvoir utiliser
    # les données dans le template
    #
    # /!\ la manipulation des éléments Python dans le template n'est pas du pure Python,
    #     c'est une syntaxe propre au langage de template de Django
    #
    #     ainsi, pour consulter dans la template une information de dictionnaire,
    #     on utilisera le "." pour définir la clé.
    #
    #     ce qui donne dans le code python
    #     ma_variable[ma_cle] = "valeur"
    #
    #     et dans le template, accédera à la valeur ainsi :
    #     {{ ma_variable.ma_cle }}

    previsions_affichage = []
    for jour in range(7):
        prevision_jour = {}
        prevision_jour["temperature"] = previsions_jour[jour]
        prevision_jour["force_vent"] = previsions_force_vent[jour]
        prevision_jour["description"] = previsions_description[jour]
        prevision_jour["jour"] = UIHelper.day_of_the_week_from_period(jour)
        prevision_jour["icon"] = "previsions/images/" + UIHelper.image_from_weather_status(previsions_description[jour])

        previsions_affichage.append(prevision_jour)

    context = {
        'ville': nom_ville,
        'previsions_affichage': previsions_affichage,
    }

    return render(request, 'previsions/display_previsions_ville.html', context)

previsions/templates/previsions/add_ville.html
{% extends 'previsions/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<form action="{% url 'previsions:add_ville'%}" method="post">
    {% csrf_token %}
    <div class="container">
        <div class="mt-6 mx-6">
        {% crispy form %}
            <button class="button is-primary" type="submit" value="Ajouter">Ajouter</button>
        </div>
    </div>
</form>
</p>

{% if save_error %}
    <p>Une erreur s'est produite lors de l'enregistrement de la ville en base de données</p>
{% else %}
    {% if is_create == False %}
    <p>La ville a bien été enregistrée en base de données</p>
    {% endif %}
{% endif %}

{% endblock content %}

previsions/templates/previsions/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Prévisions météo</title>
    <link rel="stylesheet" href="{% static 'previsions/css/styles.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v6.1.1/js/all.js"></script>
</head>
<body>
<section class="hero  is-fullheight background_hero">
    <div class="hero-head">
        <nav class="navbar has-background-link" role="navigation" aria-label="main navigation">
            <div class="navbar-brand">
                <a class="navbar-item" href="http://localhost:8000/">
                    <span class="is-uppercase has-text-weight-bold has-text-white">application météo</span>
                </a>

                <a role="button" class="navbar-burger has-text-white" aria-label="menu" aria-expanded="false"
                   data-target="navbarMenu">
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                </a>

            </div>
            <div id="navbarMenu" class="navbar-menu">
                <div class="navbar-start">
                    <a class="navbar-item has-text-white">
                        Accueil
                    </a>
                    <div class="navbar-item has-dropdown is-hoverable">
                        <a class="navbar-link has-text-white">
                            Plus...
                        </a>
                        <div class="navbar-dropdown">
                            <a class="navbar-item">
                                Configuration
                            </a>
                            <a class="navbar-item">
                                A propos
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div id="navbarMenu" class="navbar-menu is-active">
                <div class="navbar-end">
                    <div class="navbar-item">
                        <form action="{% url 'previsions:display_previsions_ville'%}" method="post">
                            {% csrf_token %}
                            <div class="block pr-6">
                                <div class="columns is-mobile is-gapless">
                                    <div class="column is-full">
                                        <div class="control">
                                            <input name="ville" class="input" type="text" placeholder="Ville...">
                                        </div>
                                    </div>
                                    <div class="column">
                                        <div class="control">
                                            <button class="button is-primary">
                                            <span class="icon">
                                              <i class="fas fa-search"></i>
                                            </span>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="navbar-item">
                        <a href="/previsions/logout" class="button is-light">
                        {% if user.is_authenticated %}
                            Se déconnecter ({{user.first_name}})
                        {% else %}
                            Se connecter
                        {% endif %}
                    </a>
                    </div>
                </div>
            </div>
        </nav>
    </div>
    <div class="hero-body ">
        {% block content %}{% endblock content %}
    </div>
    <div class="hero-foot">
        <div class="container has-text-centered">
            <p class="footer-text">
                <a href="https://coder-pour-changer-de-vie.com"
                >Vivre du Code
                    <i class="fa fa-heart fa-fw heart"></i>
                    par Nicolas Georgemel</a
                >
                <span id="version" class="has-text-white"></span>
                <span id="environment"></span>
            </p>
        </div>
    </div>
</section>
</body>
</html>

previsions/templates/previsions/departement_client.html
{% extends 'previsions/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<h1>Formulaire pour la consultation des villes d'un departement</h1>
<form action="{% url 'previsions:departement_client'%}" method="post">
    {% csrf_token %}
        {% crispy form %}

    <div class="container">
        LISTE DES VILLES
        <ul>
            {% for ville in page_obj %}
                <li>{{ ville.nom }}, {{ville.code_postal}}</li>
            {% endfor %}
        </ul>

        {% include "previsions/pagination.html" %}
    </div>
</form>


{% endblock %}

previsions/templates/previsions/departements.html
<h1>Voici la liste des villes pour le département {{nom_departement}}</h1>
<p/>
<ul>
{% for ville in villes_du_departement %}
    <li>{{ ville.nom }}, {{ville.code_postal}}</li>
{% endfor %}
</ul>

previsions/templates/previsions/display_previsions_ville.html
{% extends 'previsions/base.html' %}
{% load static %}
{% block content %}
<div class="container has-text-centered has-text-white">"
    <p class="title has-text-white">Météo de la ville de {{ville}}</p>
    <p class="subtitle has-text-white">Prévision des prochains jour</p>
    <nav class="columns is-centered">
        {% for prevision in previsions_affichage %}
        <div class="column">
            <div class="card meteo_card mx-4">
                <div class="card-header">
                    <div class="card-header-title">{{prevision.jour}}</div>
                </div>
                <div class="py-6 meteo_card_picture ">
                    <div class="has-text-centered">
                        <figure class="image is-128x128 is-inline-block">
                            <img src="{% static prevision.icon %}"></img>
                        </figure>
                    </div>
                    <p class="title is-1 has-text-white has-text-centered mt-2">
                        {{prevision.temperature|floatformat:1}}</p>
                </div>
                <div class="card-content">
                    <div class="columns is-mobile is-gapeless">
                        <div class="column">
                            <p>{{prevision.description}}</p>
                        </div>
                        <div class="column">
                                <span class="icon-text">
                                    <div class="columns is-gapless">
                                        <div class="column">
                                            <figure class="image is-32x32">
                                                <img src="{% static prevision.icon %}"></img>
                                            </figure>
                                        </div>
                                        <div class="column">
                                            <span>{{prevision.force_vent|floatformat:0}} Km/h</span>
                                        </div>
                                    </div>
                                 </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </nav>
</div>
{% endblock content %}

previsions/templates/previsions/display_villes.html
<h1>Voici la liste des villes pour le département {{departement.nom}} ({{departement.code}})</h1>
<p/>
<ul>
{% for ville in villes_du_departement %}
    <li>{{ ville.nom }}, {{ville.code_postal}}</li>
{% endfor %}
</ul>

previsions/templates/previsions/favoris.html
{% extends 'previsions/base.html' %}
{% block content %}
<div class="container">
<article class="panel is-link my-6 mx-6">
    <p class="panel-heading">
        Favoris
    </p>
    {% for ville in favoris %}
        <a class="panel-block">
        <span class="panel-icon">
          <i class="fas fa-city" aria-hidden="true"></i>
        </span>
            {{ ville }}
        </a>
    {% endfor %}
</article>
</div>
{% endblock content %}

previsions/templates/previsions/index.html
{% extends 'previsions/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
    <h1>Application de prévisions météorologiques</h1>
    <p>Bienvenue dans l'application !</p>
</div>
{% endblock content %}

previsions/templates/previsions/pagination.html
<div>
  <span>
    {% if page_obj.has_previous %}
      <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
    {% endif %}
    <span>
      Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
    </span>
    {% if page_obj.has_next %}
      <a href="?page={{ page_obj.next_page_number }}">Next</a>
    {% endif %}
  </span>
</div>

previsions/templates/previsions/select_departement.html
<h1>Formulaire pour la consultation des villes d'un departement</h1>
<form action="{% url 'previsions:display_villes'%}" method="post">
    {% csrf_token %}
    <select name="id_departement">
        {% for departement in liste_departements %}
        <option value="{{departement.id_departement}}" name="id_departement">{{departement.nom}}</option>
        {% endfor %}
    </select>
    <input type="submit">
</form>